
spring:
  application:
    name: apiserver
  security:
    user:
      name: admin
      password: admin

server:
  port: 7000
  servlet:
    context-path: /apiserver

eureka:
  server:
    enable-self-preservation: false
  instance:
    ###服务和注册中心的心跳间隔时间，默认为30s
    lease-renewal-interval-in-seconds: 10
    ###服务和注册中心的心跳超时时间，默认为90s
    lease-expiration-duration-in-seconds: 20
  client:
    fetch-registry: false
    register-with-eureka: false
    prefer-same-zone-eureka: true
    ##固定好了区域之后开始调用服务
    service-url:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@localhost:7000/apiserver/eureka/
logging:
  level:
    com.netflix: warn


