spring:
  application:
    name: gateway
  cloud:
    loadbalancer:
      retry:
        enabled: true
  datasource:
        username: root
        password: smarthomeauth2013
        #url: jdbc:mysql://192.168.0.166:3306/iot_up?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8
        url: jdbc:mysql://mysql:3306/iot_up?characterEncoding=UTF-8&useSSL=false&allowMultiQueries=true&autoReconnect=true&serverTimezone=Asia/Shanghai
        #mysql8版本以上驱动包指定新的驱动类
        driver-class-name: com.mysql.cj.jdbc.Driver
        #   数据源其他配置, 在 DruidConfig配置类中手动绑定
        type: com.alibaba.druid.pool.DruidDataSource
        initialSize: 8
        minIdle: 5
        maxActive: 20
        maxWait: 60000
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 1 FROM DUAL

server:
  port: 7002
  servlet:
    context-path: /gateway

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
    status-page-url-path: /actuator/info
    health-check-url-path: /actuator/health
  client:
    register-with-eureka: true
    fetch-registry: true
    prefer-same-zone-eureka: true
    service-url:
      defaultZone: http://admin:sola123@apiserver:7000/apiserver/eureka/

#--------------------Zuul-----------------------
zuul:
  routes:
    centre:
      path: /centre/**
      serviceId: centre
      sensitiveHeaders: "*"
      strip-prefix: false
    auth:
      path: /auth/**
      serviceId: auth
      sensitiveHeaders: "*"
      strip-prefix: false
    estate:
      path: /estate/**
      serviceId: estate
      sensitiveHeaders: "*"
      strip-prefix: false
    wt:
      path: /wt/**
      serviceId: wt
      sensitiveHeaders: "*"
      strip-prefix: false
  retryable: false
  ignored-services: "*"
  ribbon:
    eager-load:
      enabled: true
  host:
    connect-timeout-millis: 3000  # 连接建立的超时时间；，默认为2000ms
    socket-timeout-millis: 3000  # 响应超时时间，默认为10000ms
  add-proxy-headers: true
  semaphore:
    max-semaphores: 5000 #并发信号量


#---------------------OAuth2---------------------
security:
  oauth2:
    client:
      access-token-uri: http://gateway:${server.port}/gateway/centre/oauth/token
      user-authorization-uri: http://gateway:${server.port}/gateway/centre/oauth/authorize
      client-id: web
    resource:
      user-info-uri:  http://gateway:${server.port}/gateway/centre/api/authority
      prefer-token-info: false

#----------------------超时配置-------------------
ribbon:
  ReadTimeout: 20000                 #请求处理超时时间Ribbon 总时间ribbonTimeout = (ribbonReadTimeout + ribbonConnectTimeout) * (maxAutoRetries + 1) * (maxAutoRetriesNextServer + 1)
  ConnectTimeout: 20000              #请求连接超时时间
  MaxTotalHttpConnections: 1000     #最大http连接数
  MaxConnectionsPerHost: 100        #每个host最大连接数
  MaxAutoRetries: 0                 #最大重试次数
  MaxAutoRetriesNextServer: 0      #切换实例的重试次数
  eureka:
    enabled: true

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 60000  #发生熔断的超时时间
          semaphore:
            maxConcurrentRequests: 5000     #信号量大小
          #strategy: SEMAPHORE                #隔离策略
        circuitBreaker:
            sleepWindowInMilliseconds:  5000   #短路多久以后开始尝试是否恢复