spring:
  application:
    name: gateway
  cloud:
    loadbalancer:
      retry:
        enabled: true

server:
  port: 7001
  servlet:
    context-path: /gateway

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
    status-page-url-path: /actuator/info
    health-check-url-path: /actuator/health
  client:
    register-with-eureka: true
    fetch-registry: true
    prefer-same-zone-eureka: true
    service-url:
      defaultZone: http://admin:admin@localhost:7000/apiserver/eureka/

#--------------------Zuul-----------------------
zuul:
  routes:
    auth:
      path: /auth/**
      serviceId: auth
      sensitiveHeaders: "*"
      strip-prefix: false
    test:
      path: /test/**
      serviceId: test
      sensitiveHeaders: "*"
      strip-prefix: false
    user:
      path: /user/**
      serviceId: user
      sensitiveHeaders: "*"
      strip-prefix: false
    guard:
      path: /guard/**
      serviceId: guard
      sensitiveHeaders: "*"
      strip-prefix: false
  retryable: false
  ignored-services: "*"
  ribbon:
    eager-load:
      enabled: true
  host:
    connect-timeout-millis: 3000  # 连接建立的超时时间；，默认为2000ms
    socket-timeout-millis: 3000  # 响应超时时间，默认为10000ms
  add-proxy-headers: true
  semaphore:
    max-semaphores: 5000 #并发信号量


#---------------------OAuth2---------------------
security:
  oauth2:
    client:
      access-token-uri: http://localhost:${server.port}/gateway/auth/oauth/token
      user-authorization-uri: http://localhost:${server.port}/gateway/auth/oauth/authorize
      client-id: web
    resource:
      user-info-uri:  http://localhost:${server.port}/gateway/auth/api/authority
      prefer-token-info: false

#----------------------超时配置-------------------
ribbon:
  ReadTimeout: 60000                 #请求处理超时时间
  ConnectTimeout: 60000              #请求连接超时时间
  MaxTotalHttpConnections: 1000     #最大http连接数
  MaxConnectionsPerHost: 100        #每个host最大连接数
  MaxAutoRetries: 10                 #最大重试次数
  MaxAutoRetriesNextServer: 10      #切换实例的重试次数
  eureka:
    enabled: true

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 60000  #发生熔断的超时时间
          semaphore:
            maxConcurrentRequests: 5000     #信号量大小
          #strategy: SEMAPHORE                #隔离策略
        circuitBreaker:
            sleepWindowInMilliseconds:  5000   #短路多久以后开始尝试是否恢复